name: Pacman contribution graph

on:
  schedule:
    # Executa todos os dias às 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-pacman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install -g pacman-canvas

      - name: Generate contribution graph (light theme)
        run: pacman-canvas --output ./output/pacman-contribution-graph.svg --dark false

      - name: Generate contribution graph (dark theme)
        run: pacman-canvas --output ./output/pacman-contribution-graph-dark.svg --dark true

      - name: Commit & push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./output/pacman-contribution-graph*.svg
          git commit -m "Atualiza gráfico Pacman contribution"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
